### ISSUE TITLE
Best way to change/update `configuration_store` options using a web form?

### ISSUE THREAD

**Issue by coryschires** [metaskills/store_configurable#6]
I'm refactoring configuration options in my app. Perviously we'd been using separate columns to store each option. Instead, I'd really like to use `store_configurable`.

As is probably common, I need users to be able to update/change their configuration options using a form (e.g. checkboxes, etc). When using database columns, this is simple.

**Question:** How do set/update `store_configurable` options within a standard Rails form?

I believe I can hack together a decent solution. I just wanted to first check if there a conventional solution for this problem? I presume it's a common enough use case.

**Comment by metaskills** [comment]
This is more a question for stack overflow since what you are really asking is how to do low level form construction and parameter parsing. So let's start at the end, this plugin and work backward. First, I have setup StoreConfigurable to allow namespace keys as the docs say and these can be assigned a hash. So an example from my test file.

``` ruby
plugin_params = {:sort => 'asc', :column => 'id', :etc => 'foo'}
user_ken.config.plugin.options = plugin_params
```

Will nest those just nicely. So anything in a hash can be stored easily. Sounds like you want to assign a hash of key values who's keys are columns and values are either true/false. You can google around for rails check box tag helper and form submissions and find what you need. About the only issue I see, depending on how you go is that you want to cast the values that come in from the params to real true/false values, vs "1"/"0" strings or "true"/"false" strings.
