### ISSUE TITLE
Rails4 Compatibility

### ISSUE THREAD

**Issue by andyl** [metaskills/store_configurable#8]
Has anyone gotten store_configurable to work with Ruby2 / Rails4 ??

**Comment by metaskills** [comment]
Let's update the tests and find out. I've recently been using Appraisal to test multiple Rails/ActiveRecord versions. See this project for a simple example. https://github.com/customink/gigo

**Comment by metaskills** [comment]
I have updated master to focus on 4.0 and 4.1, but all tests fail with 

```
SystemStackError: stack level too deep
./lib/store_configurable/read.rb:26
```

**Comment by georgediaz88** [comment]
I'm trying to get this to work as well as we try to upgrade our app to Rails4. One thing that changed in AR 4.1.8 is the `#unserialize` method in serialization.rb.

It now takes an argument as such:

``` ruby
# in /activerecord-4.1.8/lib/active_record/attribute_methods/serialization.rb
        def unserialize(v)
          self.state = :unserialized
          self.value = coder.load(v)
        end
```

I'd recomment in the Rails4 compatible gem version you reflect this by something like:

``` ruby
# in lib/store_configurable/serialization.rb
    def unserialize(v)
      self.state = :unserialized
      self.value = coder.load(v, __store_configurable_owner__)
    end
```

That fixes an issue if you uncover the `stack level too deep` issue. Now, onto that....

I have not solved this one just yet. So, I wanted to brain dump here. The `stack level too deep` error has to be due to some circular issue. So, you were spot on focusing in `read.rb` in your gem.

It looks like something changed in AR's `#read_attribute` method for this not to work or my other guess, AR is being strict now and _not_ allowing deep recursion (infinite loop).

I'm trying to understand more of the code (my lack of serialization in AR) and see a loop forming by:

``` ruby
   def config
     _config.__store_configurable_owner__ = self
     _config
   end

    def _config
      attrib = @attributes['_config']
      unless attrib.respond_to?(:__store_configurable_owner__)
        attrib.extend Serialization
        attrib.__store_configurable_owner__ = self
      end
      super
    end

  def read_attribute(attr_name)
    config
    super
 end
```

^^ So, first I noticed in `#config` calling `_config.__store_configurable_owner__ = self` will call the `#_config` method which then calls super which calls the `#read_attribute` method which calls `#config` again which is where we started and thus causing an infinite loop. So, I think trying to re-work these methods to make that work should fix it. Maybe `#read_attribute` should change to do the stuff in `#_config` that it must? I'd start there but again, with some lack of familiarity with this code just throwing ideas. Hoping for some help so we can get a build going with the aforementioned suggested change and any you may come up w/ for `#read_attribute` on a rails4 branch. Okay, I'll be following this issue if you have any more questions.

**Comment by metaskills** [comment]
@georgediaz88 Thanks for the comment. I'm working on this now and will get back to you in a day or two.

**Comment by metaskills** [comment]
I am really close. One more test to pass. Stay tuned.

**Comment by georgediaz88** [comment]
Awesome. Thanks for keeping us updated.

**Comment by metaskills** [comment]
So a bit of how I got 4.0 and 4.1 to work. This `Attribute` class (https://github.com/rails/rails/blob/4-0-stable/activerecord/lib/active_record/attribute_methods/serialization.rb#L89-L107). It is instantiated in two places. First when [writing to the DB column](https://github.com/rails/rails/blob/4-0-stable/activerecord/lib/active_record/attribute_methods/serialization.rb#L131) and second [when reading](https://github.com/rails/rails/blob/4-0-stable/activerecord/lib/active_record/attribute_methods/serialization.rb#L121). I had to change the `StoreConfigurable::Object` load method to take an optional owner. There was no easy we to change extend the `Attribute` class for the DB write, but that is OK, the owner is moot at that point. 

I have published a new 4.0.0 gem that will work with ActiveRecord 4.0 and 4.1. There are many changes in 4.2 and I will open another issue to get that solved. Cheers!

**Comment by andyl** [comment]
@metaskills thanks for addressing 4.x compatibility!  I just upgraded to Rails4.2, and will give it a test when #11 is closed.

**Comment by metaskills** [comment]
NP! 4.2 is broken, I have added an appraisal and viewed the ActiveSupport/ActiveRecord source. I think 4.2 will require some significant re-engineering as it has a new Type class that does what Attribute was doing... but better.

**Comment by andyl** [comment]
Here's a PR that AFAIK removes the need to use `*_will_change` in Rails4.2.

https://github.com/rails/rails/pull/15674

**Comment by georgediaz88** [comment]
@metaskills thanks again for the quick effort to get this _early Rails4 compatible!_ I'll test it out. Also, good to see an issue opened for 4.2 as well.
